### ISSUE TITLE
Control Time Stats

### ISSUE THREAD

**Issue by blackred360** [mtoto/ufc.stats#3] opened 2021-03-21 18:29 UTC
Hello - is it possible to add the control time stats for all fights to this data set from now on? It replaced the passes/advances statistic late last year in the UFC's numbers presented on UFCStats and other sites like ESPN.

**Comment by asifzubair** [comment] 2021-04-18 18:56
Hi @blackred360 , is `refresh_data()` working for you ?

**Comment by mtoto** [comment] 2023-02-04 20:16
@asifzubair sorry for being late, `refresh_data()` should work correctly now!

**Comment by mtoto** [comment] 2023-02-04 20:17
Duplicate of #6

**Closed as completed by mtoto** 2023-02-04 20:17 UTC

**Comment by BalazsBokros** [comment] 2023-04-28 07:38
Hi @mtoto ! I am a bit new to R however the refresh_data() function does not seem to work for me. I get the error message:
"Error: Directory 'C:/Users/BalĂˇzs/Documents/R/win-library/4.1/ufc.stats' does not exist." There may be a problem with my Username containing special characters, however I am only experiencing an issue like this for the first time. 
I was trying to get the control times added to my database as it was indicated that this function would. However even in the downloaded database ("ufc_stats.RDA") in the package directory here on github the control times are not included, which signal to me that even if i was able to run the function, it would not add the control times. Can you help?
